apiVersion: v1
kind: Service
metadata:
  name: nodeport-whoami
spec:
  type: NodePort
  selector:
    app: whoami # Instructs the service which pods to look for, in this case ones with a lable of app that is set to whoami
  ports:
    - nodePort: 30001 # Port on the hostmachine/worker node the NodePort service will be accessible on
      port: 80 # Port of the NodePort service itself
      targetPort: 80 # Port on the targeted