apiVersion: v1
kind: ConfigMap
metadata:
  name: asp-net-sample-config
data:
  appsettings.k8s.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ApiResponseValue": "Hello from the configmap!"
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
type: Qpaque # Tells K8s that this is unstructued data, alternatives could be ServiceAccount or ImagePullSecret
data:
  db_password: bXktc3VwZXItc2VjcmV0LWRiLXBhc3N3b3Jk