apiVersion: v1
kind: ConfigMap
metadata:
  name: asp-net-sample-config
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ApiResponseValue": "Hello from the configmap!"
    }
    