apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-net-app-repo-github
  labels:
    app: asp-net-app-repo
spec:
  selector:
    matchLabels:
        app: asp-net-app-repo
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: asp-net-app
    spec:
      volumes:
        - name: configuration-volume
          configMap:
            name: asp-net-sample-config
      containers:
        - name: asp-net-app-repo
          image: 521936459218.dkr.ecr.eu-west-1.amazonaws.com/asp-net-app-repo:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: "DB_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: application-secrets
                key: db_password
          volumeMounts:
            - name: configuration-volume
              mountPath: /app/appsettings.k8s.json
              subPath: appsettings.k8s.json