apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-net-app-github
  labels:
    app: asp-net-app
spec:
  selector:
    matchLabels:
        app: asp-net-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: asp-net-app
    spec:
      volumes:
        - name: configuration-volume
          configMap:
            name: asp-net-sample-config
      containers:
        - name: asp-net-app
          image: 521936459218.dkr.ecr.eu-west-1.amazonaws.com/asp-net-app:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: configuration-volume
              mountPath: /