apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  color: red
  sample-config.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
    