apiVersion: v1
kind: Pod
metadata:
  name: two-containers-with-empty-dir
  annotations:
    tier: webserver 
  labels:
    name: volume-pod
    tier: backend
    environment: prod
    team: blue-team
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts: 
    - mountPath: /var/config
      name: host-path-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"  
  - name: busybox-container
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  # Can also specify mounts from the host system, the worker node
  # This won't work on Fargate
  volumes:
  - name: host-path-volume
    hostPath:
      path: /tmp

