apiVersion: v1
kind: Pod
metadata:
  name: two-containers-with-empty-dir
  # annotations allow additional contextual metadata to be added. Support email to contact for an outage etc.
  annotations:
    tier: webserver 
  # Labels help build relationships between pods and can be used with kubectl to query all pods with a given label
  labels:
    name: volume-pod
    tier: backend
    environment: prod
    team: blue-team
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    # Can mount volumes to a specific directory
    volumeMounts: 
    - mountPath: /var/i-am-an-empty-dir-volume
      name: empty-dir-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"  
  - name: busybox-container
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"]
    volumeMounts: 
    - mountPath: /var/i-am-an-empty-dir-volume
      name: empty-dir-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  # Note, this is an ephermal volume
  volumes:
  - name: empty-dir-volume
    emptyDir: {}

